name: build

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Lint
        run: npm run lint

      - name: Server unit tests
        run: npm run test

      - name: Package
        run: npx vsce package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: '*.vsix'
          if-no-files-found: error

      - name: Upload extension to github release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: '*.vsix'
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish packaged extension
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          npx vsce publish -i *.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
